package resistor

///////////////////////////////////////////////////////////////////////////////
// Inference Result
///////////////////////////////////////////////////////////////////////////////

/*
InferenceResult represents the inferred characteristics of an
observed resistor.

Spec:

	Electrical characteristics either deterministically decoded
	or inferred via heuristic rules.

VoltageRating:

	Conservative estimate derived from physical characteristics.

Meta:

	Contains assumptions made and overall confidence score.

Confidence Model:

	Confidence ∈ [0.0 – 1.0]

	Deterministic facts contribute weight = 1.0
	Heuristic rules contribute weight ∈ (0,1)

Final confidence is a weighted average of all applied rules.
*/
type InferenceResult struct {
	Spec          ResistorSpec
	VoltageRating float64
	Meta          InferenceMeta
}

///////////////////////////////////////////////////////////////////////////////
// Internal Rule System
///////////////////////////////////////////////////////////////////////////////

/*
inferenceContribution represents a partial inference result
generated by a rule.

Each rule may infer one or more properties.
*/
type inferenceContribution struct {
	Spec          ResistorSpec
	VoltageRating float64
	Assumption    string
	Weight        float64
}

/*
InferenceRule defines a single heuristic rule.

Weight:

	Relative confidence in this rule (0.0–1.0)

Apply:

	Returns a contribution and whether rule applied.
*/
type InferenceRule struct {
	Name   string
	Weight float64
	Apply  func(obs ObservedResistor) (inferenceContribution, bool)
}

///////////////////////////////////////////////////////////////////////////////
// Public Inference Engine
///////////////////////////////////////////////////////////////////////////////

/*
InferResistor attempts to infer properties of an observed resistor.

Process:

1. Extract deterministic facts:
  - Decode color bands (if present)
  - Decode SMD marking (if present)

2. Apply heuristic rules:
  - Body color → resistor type
  - Band count → tolerance hint
  - Physical length → power rating
  - Package type → power estimate

3. Aggregate results:
  - Deterministic values override heuristics
  - Heuristic contributions averaged by weight
  - Confidence computed as weighted mean

This engine is intentionally transparent and deterministic.
*/
func InferResistor(obs ObservedResistor) (InferenceResult, error) {

	var result InferenceResult
	var assumptions []string

	confidence := 0.0

	// ---------------------------------------------------------
	// 1. Deterministic Extraction
	// ---------------------------------------------------------

	// Decode color bands
	if len(obs.Bands) == 4 || len(obs.Bands) == 5 || len(obs.Bands) == 6 {
		spec, err := DecodeBands(obs.Bands)
		if err == nil {

			result.Spec = spec
			assumptions = append(assumptions,
				"Resistance and tolerance determined from color bands")

			// Deterministic fact → weight = 1.0
			confidence = 1 - (1-confidence)*(1-1.0)
		}
	}

	// Decode SMD marking (only if resistance still unknown)
	if obs.Marking != "" && result.Spec.ResistanceOhms == 0 {
		spec, err := DecodeSMD(obs.Marking)
		if err == nil {

			result.Spec.ResistanceOhms = spec.ResistanceOhms

			assumptions = append(assumptions,
				"Resistance determined from SMD marking")

			confidence = 1 - (1-confidence)*(1-1.0)
		}
	}

	// ---------------------------------------------------------
	// 2. Heuristic Rules
	// ---------------------------------------------------------

	rules := defaultInferenceRules()

	for _, rule := range rules {

		contrib, applied := rule.Apply(obs)
		if !applied {
			continue
		}

		appliedEffectively := false

		// Only apply if field not already known
		if result.Spec.Type == "" && contrib.Spec.Type != "" {
			result.Spec.Type = contrib.Spec.Type
			appliedEffectively = true
		}

		if result.Spec.PowerWatts == 0 && contrib.Spec.PowerWatts != 0 {
			result.Spec.PowerWatts = contrib.Spec.PowerWatts
			appliedEffectively = true
		}

		if result.VoltageRating == 0 && contrib.VoltageRating != 0 {
			result.VoltageRating = contrib.VoltageRating
			appliedEffectively = true
		}

		if result.Spec.TolerancePct == 0 && contrib.Spec.TolerancePct != 0 {
			result.Spec.TolerancePct = contrib.Spec.TolerancePct
			appliedEffectively = true
		}

		// If rule did not actually modify state, ignore it
		if !appliedEffectively {
			continue
		}

		if contrib.Assumption != "" {
			assumptions = append(assumptions, contrib.Assumption)
		}

		// Monotonic confidence accumulation
		confidence = 1 - (1-confidence)*(1-rule.Weight)
	}

	// ---------------------------------------------------------
	// 3. Finalize
	// ---------------------------------------------------------

	result.Meta.Assumptions = assumptions
	result.Meta.Confidence = confidence

	return result, nil
}

///////////////////////////////////////////////////////////////////////////////
// Default Rule Set
///////////////////////////////////////////////////////////////////////////////

func defaultInferenceRules() []InferenceRule {

	lengthRule := func(min, max, watts, volts, weight float64, label string) InferenceRule {
		return InferenceRule{
			Name:   label,
			Weight: weight,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.LengthMM >= min && obs.LengthMM <= max {
					return inferenceContribution{
						Spec:          ResistorSpec{PowerWatts: watts},
						VoltageRating: volts,
						Assumption:    label,
						Weight:        weight,
					}, true
				}
				return inferenceContribution{}, false
			},
		}
	}

	return []InferenceRule{

		// =================================================
		// BODY COLOR → TYPE
		// =================================================

		{
			Name:   "Blue body → Metal film",
			Weight: 0.7,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.BodyColor == Blue {
					return inferenceContribution{
						Spec:       ResistorSpec{Type: MetalFilm},
						Assumption: "Blue body assumed metal film",
						Weight:     0.7,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
		{
			Name:   "Beige/Tan body → Carbon film",
			Weight: 0.6,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.BodyColor == Color("beige") || obs.BodyColor == Color("tan") {
					return inferenceContribution{
						Spec:       ResistorSpec{Type: CarbonFilm},
						Assumption: "Beige/tan body assumed carbon film",
						Weight:     0.6,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
		{
			Name:   "Green body → Metal oxide",
			Weight: 0.6,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.BodyColor == Green {
					return inferenceContribution{
						Spec:       ResistorSpec{Type: MetalOxide},
						Assumption: "Green body assumed metal oxide",
						Weight:     0.6,
					}, true
				}
				return inferenceContribution{}, false
			},
		},

		// =================================================
		// BAND COUNT → TOLERANCE (IF UNKNOWN)
		// =================================================

		{
			Name:   "4 bands → ±5%",
			Weight: 0.6,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if len(obs.Bands) == 4 {
					return inferenceContribution{
						Spec:       ResistorSpec{TolerancePct: 5},
						Assumption: "4 bands assumed ±5% tolerance",
						Weight:     0.6,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
		{
			Name:   "5 bands → ±1%",
			Weight: 0.6,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if len(obs.Bands) == 5 {
					return inferenceContribution{
						Spec:       ResistorSpec{TolerancePct: 1},
						Assumption: "5 bands assumed ±1% tolerance",
						Weight:     0.6,
					}, true
				}
				return inferenceContribution{}, false
			},
		},

		// =================================================
		// LENGTH → POWER
		// =================================================

		lengthRule(2, 3, 0.0625, 100, 0.6, "Length 2-3mm assumed 1/16W"),
		lengthRule(3, 4, 0.125, 150, 0.6, "Length 3-4mm assumed 1/8W"),
		lengthRule(5, 7, 0.25, 200, 0.7, "Length 5-7mm assumed 1/4W"),
		lengthRule(8, 10, 0.5, 300, 0.8, "Length 8-10mm assumed 1/2W"),
		lengthRule(11, 13, 1.0, 500, 0.85, "Length 11-13mm assumed 1W"),
		lengthRule(15, 18, 2.0, 750, 0.9, "Length 15-18mm assumed 2W"),

		// =================================================
		// SMD PACKAGE SIZE → POWER
		// =================================================

		{
			Name:   "0402 → 1/16W",
			Weight: 0.8,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.Package == SMD0402 {
					return inferenceContribution{
						Spec:          ResistorSpec{PowerWatts: 0.0625},
						VoltageRating: 25,
						Assumption:    "0402 package assumed 1/16W rating",
						Weight:        0.8,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
		{
			Name:   "0603 → 0.1W",
			Weight: 0.8,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.Package == SMD0603 {
					return inferenceContribution{
						Spec:          ResistorSpec{PowerWatts: 0.1},
						VoltageRating: 50,
						Assumption:    "0603 package assumed 0.1W rating",
						Weight:        0.8,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
		{
			Name:   "0805 → 0.125W",
			Weight: 0.8,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.Package == SMD0805 {
					return inferenceContribution{
						Spec:          ResistorSpec{PowerWatts: 0.125},
						VoltageRating: 100,
						Assumption:    "0805 package assumed 0.125W rating",
						Weight:        0.8,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
		{
			Name:   "1206 → 0.25W",
			Weight: 0.85,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.Package == SMD1206 {
					return inferenceContribution{
						Spec:          ResistorSpec{PowerWatts: 0.25},
						VoltageRating: 200,
						Assumption:    "1206 package assumed 0.25W rating",
						Weight:        0.85,
					}, true
				}
				return inferenceContribution{}, false
			},
		},

		// =================================================
		// CROSS-SIGNAL REINFORCEMENT
		// =================================================

		{
			Name:   "Blue + 5 band reinforcement",
			Weight: 0.2,
			Apply: func(obs ObservedResistor) (inferenceContribution, bool) {
				if obs.BodyColor == Blue && len(obs.Bands) == 5 {
					return inferenceContribution{
						Assumption: "Blue body + 5 bands reinforced precision metal film assumption",
						Weight:     0.2,
					}, true
				}
				return inferenceContribution{}, false
			},
		},
	}
}
