package resistor

///////////////////////////////////////////////////////////////////////////////
// Inference Result
///////////////////////////////////////////////////////////////////////////////

/*
InferenceResult represents the inferred characteristics of an
observed resistor.

Spec:
    Electrical characteristics either deterministically decoded
    or inferred via heuristic rules.

VoltageRating:
    Conservative estimate derived from physical characteristics.

Meta:
    Contains assumptions made and overall confidence score.

Confidence Model:

    Confidence ∈ [0.0 – 1.0]

    Deterministic facts contribute weight = 1.0
    Heuristic rules contribute weight ∈ (0,1)

Final confidence is a weighted average of all applied rules.
*/
type InferenceResult struct {
    Spec          ResistorSpec
    VoltageRating float64
    Meta          InferenceMeta
}

///////////////////////////////////////////////////////////////////////////////
// Internal Rule System
///////////////////////////////////////////////////////////////////////////////

/*
inferenceContribution represents a partial inference result
generated by a rule.

Each rule may infer one or more properties.
*/
type inferenceContribution struct {
    Spec          ResistorSpec
    VoltageRating float64
    Assumption    string
    Weight        float64
}

/*
InferenceRule defines a single heuristic rule.

Weight:
    Relative confidence in this rule (0.0–1.0)

Apply:
    Returns a contribution and whether rule applied.
*/
type InferenceRule struct {
    Name   string
    Weight float64
    Apply  func(obs ObservedResistor) (inferenceContribution, bool)
}

///////////////////////////////////////////////////////////////////////////////
// Public Inference Engine
///////////////////////////////////////////////////////////////////////////////

/*
InferResistor attempts to infer properties of an observed resistor.

Process:

1. Extract deterministic facts:
      - Decode color bands (if present)
      - Decode SMD marking (if present)

2. Apply heuristic rules:
      - Body color → resistor type
      - Band count → tolerance hint
      - Physical length → power rating
      - Package type → power estimate

3. Aggregate results:
      - Deterministic values override heuristics
      - Heuristic contributions averaged by weight
      - Confidence computed as weighted mean

This engine is intentionally transparent and deterministic.
*/
func InferResistor(obs ObservedResistor) (InferenceResult, error) {

    var result InferenceResult
    var assumptions []string

    confidence := 0.0

    // ---------------------------------------------------------
    // 1. Deterministic Extraction
    // ---------------------------------------------------------

    // Decode color bands
    if len(obs.Bands) == 4 || len(obs.Bands) == 5 {
        spec, err := DecodeBands(obs.Bands)
        if err == nil {

            result.Spec.ResistanceOhms = spec.ResistanceOhms
            result.Spec.TolerancePct = spec.TolerancePct

            assumptions = append(assumptions,
                "Resistance and tolerance determined from color bands")

            // Deterministic fact → weight = 1.0
            confidence = 1 - (1-confidence)*(1-1.0)
        }
    }

    // Decode SMD marking (only if resistance still unknown)
    if obs.Marking != "" && result.Spec.ResistanceOhms == 0 {
        spec, err := DecodeSMD(obs.Marking)
        if err == nil {

            result.Spec.ResistanceOhms = spec.ResistanceOhms

            assumptions = append(assumptions,
                "Resistance determined from SMD marking")

            confidence = 1 - (1-confidence)*(1-1.0)
        }
    }

    // ---------------------------------------------------------
    // 2. Heuristic Rules
    // ---------------------------------------------------------

    rules := defaultInferenceRules()

    for _, rule := range rules {

        contrib, applied := rule.Apply(obs)
        if !applied {
            continue
        }

        appliedEffectively := false

        // Only apply if field not already known
        if result.Spec.Type == "" && contrib.Spec.Type != "" {
            result.Spec.Type = contrib.Spec.Type
            appliedEffectively = true
        }

        if result.Spec.PowerWatts == 0 && contrib.Spec.PowerWatts != 0 {
            result.Spec.PowerWatts = contrib.Spec.PowerWatts
            appliedEffectively = true
        }

        if result.VoltageRating == 0 && contrib.VoltageRating != 0 {
            result.VoltageRating = contrib.VoltageRating
            appliedEffectively = true
        }

        if result.Spec.TolerancePct == 0 && contrib.Spec.TolerancePct != 0 {
            result.Spec.TolerancePct = contrib.Spec.TolerancePct
            appliedEffectively = true
        }

        // If rule did not actually modify state, ignore it
        if !appliedEffectively {
            continue
        }

        if contrib.Assumption != "" {
            assumptions = append(assumptions, contrib.Assumption)
        }

        // Monotonic confidence accumulation
        confidence = 1 - (1-confidence)*(1-rule.Weight)
    }

    // ---------------------------------------------------------
    // 3. Finalize
    // ---------------------------------------------------------

    result.Meta.Assumptions = assumptions
    result.Meta.Confidence = confidence

    return result, nil
}

///////////////////////////////////////////////////////////////////////////////
// Default Rule Set
///////////////////////////////////////////////////////////////////////////////

func defaultInferenceRules() []InferenceRule {

    return []InferenceRule{

        // -------------------------------------------------
        // Body Color → Type
        // -------------------------------------------------
        {
            Name:   "Blue body → Metal film",
            Weight: 0.7,
            Apply: func(obs ObservedResistor) (inferenceContribution, bool) {

                if obs.BodyColor == Blue {
                    return inferenceContribution{
                        Spec: ResistorSpec{
                            Type: MetalFilm,
                        },
                        Assumption: "Blue body assumed metal film",
                        Weight:     0.7,
                    }, true
                }
                return inferenceContribution{}, false
            },
        },

        // -------------------------------------------------
        // Band Count → Tolerance Hint
        // -------------------------------------------------
        {
            Name:   "5 bands → Likely ±1%",
            Weight: 0.6,
            Apply: func(obs ObservedResistor) (inferenceContribution, bool) {

                if len(obs.Bands) == 5 {
                    return inferenceContribution{
                        Spec: ResistorSpec{
                            TolerancePct: 1,
                        },
                        Assumption: "5 bands assumed ±1% tolerance",
                        Weight:     0.6,
                    }, true
                }
                return inferenceContribution{}, false
            },
        },

        // -------------------------------------------------
        // Length → Power Estimate
        // -------------------------------------------------
        {
            Name:   "Length ≈6mm → 1/4W",
            Weight: 0.6,
            Apply: func(obs ObservedResistor) (inferenceContribution, bool) {

                if obs.LengthMM >= 5.5 && obs.LengthMM <= 7.0 {
                    return inferenceContribution{
                        Spec: ResistorSpec{
                            PowerWatts: 0.25,
                        },
                        VoltageRating: 200, // conservative estimate
                        Assumption:    "Length ~6mm assumed 1/4W resistor",
                        Weight:        0.6,
                    }, true
                }
                return inferenceContribution{}, false
            },
        },

        // -------------------------------------------------
        // SMD Package → Power Estimate
        // -------------------------------------------------
        {
            Name:   "0603 package → 0.1W",
            Weight: 0.7,
            Apply: func(obs ObservedResistor) (inferenceContribution, bool) {

                if obs.Package == SMD {
                    return inferenceContribution{
                        Spec: ResistorSpec{
                            PowerWatts: 0.1,
                        },
                        VoltageRating: 50,
                        Assumption:    "SMD package assumed ~0.1W rating",
                        Weight:        0.7,
                    }, true
                }
                return inferenceContribution{}, false
            },
        },
    }
}